list = [
        {
            "id": 1,
            "nombre": "Jason",
            "altura": 1.75,
            "habilidad": "Correr mas rapido cuando lo persiguen",
            "imagen": "https://imagenes-pokeneas.s3.us-east-1.amazonaws.com/1.jpg",
            "frase": "La vida es un juego, y yo soy el jugador.",
        },
        {
            "id": 2,
            "nombre": "Javier",
            "altura": 1.80,
            "habilidad": "Robarle la comida a los demas",
            "imagen": "https://imagenes-pokeneas.s3.us-east-1.amazonaws.com/2.jpg",
            "frase": "El que no arriesga un sancocho, no gana una bandeja paisa.",
        },
        {
            "id": 3,
            "nombre": "Juan",
            "altura": 1.85,
            "habilidad": "Caminar sin que lo vean",
            "imagen": "https://imagenes-pokeneas.s3.us-east-1.amazonaws.com/3.jpg",
            "frase": "Más vale una moto prestada que mil buses llenos.",
        },
        {
            "id": 4,
            "nombre": "Bryan",
            "altura": 1.90,
            "habilidad": "Escuchar a la policia desde lejos",
            "imagen": "https://imagenes-pokeneas.s3.us-east-1.amazonaws.com/4.jpg",
            "frase": "Amor que no se demuestra con tinto, no es amor del bueno.",
        },
        {
            "id": 5,
            "nombre": "Esneider",
            "altura": 1.95,
            "habilidad": "Abrir puertas con la mente",
            "imagen": "https://imagenes-pokeneas.s3.us-east-1.amazonaws.com/5.jpg",
            "frase": "No hay mal que un pastel de pollo no cure.",
        },
        {
            "id": 6,
            "nombre": "Stiven",
            "altura": 2.00,
            "habilidad": "Tomarse 4 cervezas en 1 minuto",
            "imagen": "https://imagenes-pokeneas.s3.us-east-1.amazonaws.com/6.JPG",
            "frase": "No hay GPS que te guíe si no sabés para dónde vas",
        },
        {
            "id": 7,
            "nombre": "Salomon",
            "altura": 2.05,
            "habilidad": "Cantar en la ducha",
            "imagen": "https://imagenes-pokeneas.s3.us-east-1.amazonaws.com/7.jpg",
            "frase": "La vida es como un chiste, a veces no tiene sentido.",
        },
    ]
